# Build Benchmark Instrumentation Application on Travis CI - https://travis-ci.org/

language: cpp

sudo: required

cache:
  - apt

compiler:
  - gcc

before_install:
  - sh build/travis/installDependencies.sh

script:
  - mkdir cmake_build && cd cmake_build && cmake ..
